services:
  auth_service:
    # Usa o Dockerfile localizado no diretório atual (./)
    build: .  
    # Nome do container
    container_name: auth_service  
    # Define o diretório de trabalho no container
    working_dir: /app  
    # Expõe a porta 8000 do container para a máquina host
    ports:
      - "8000:8000"  
    # Mapeia todo o projeto local para dentro do container (sincroniza alterações)
    volumes:
      - .:/app  
    environment:
      - JWT_SECRET=${JWT_SECRET}
      - ENV=${ENV}  # Define a variável de ambiente para indicar ambiente de desenvolvimento
      - MONGO_DB_NAME=${MONGO_DB_NAME}
      
    # Comando para iniciar a aplicação FastAPI
    command: uvicorn auth_service.main:app --host 0.0.0.0  --port 8000 --reload

    depends_on:
      - mongodb

  mongodb:
    image: mongo:7
    container_name: mongodb
    restart: always
    ports:
      - "27018:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: